// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7w7gRSfbKuea2JoSEtVei3yZ8Xk0lkg',
    appId: '1:825151978896:web:41daad96b9275095580715',
    messagingSenderId: '825151978896',
    projectId: 'travelapp-65855',
    authDomain: 'travelapp-65855.firebaseapp.com',
    storageBucket: 'travelapp-65855.appspot.com',
    measurementId: 'G-RZ1WXC4JN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWcyAMJp_m8dN4icqhQJ9xGx917VMUy6s',
    appId: '1:825151978896:android:d7244266e5827e90580715',
    messagingSenderId: '825151978896',
    projectId: 'travelapp-65855',
    storageBucket: 'travelapp-65855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPcjVUluVQwi2JDo05g3cmkI4Wxmvd_Yo',
    appId: '1:825151978896:ios:62644b5194506a20580715',
    messagingSenderId: '825151978896',
    projectId: 'travelapp-65855',
    storageBucket: 'travelapp-65855.appspot.com',
    iosBundleId: 'com.example.travelappuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPcjVUluVQwi2JDo05g3cmkI4Wxmvd_Yo',
    appId: '1:825151978896:ios:62644b5194506a20580715',
    messagingSenderId: '825151978896',
    projectId: 'travelapp-65855',
    storageBucket: 'travelapp-65855.appspot.com',
    iosBundleId: 'com.example.travelappuser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo7w7gRSfbKuea2JoSEtVei3yZ8Xk0lkg',
    appId: '1:825151978896:web:e14235abd540bd07580715',
    messagingSenderId: '825151978896',
    projectId: 'travelapp-65855',
    authDomain: 'travelapp-65855.firebaseapp.com',
    storageBucket: 'travelapp-65855.appspot.com',
    measurementId: 'G-1PT6V2BRC0',
  );
}
